### ISSUE TITLE
java.lang.NoClassDefFoundError: scala.collection.immutable.Vector

### ISSUE THREAD

**Issue by samirissa00** [PredictionIO/template-java-parallel-ecommercerecommendation#3]
../pio build --verbose
/opt/cloudera/parcels/CDH is probably an Apache Spark development tree. Please make sure you are using at least 1.3.0.
Exception in thread "main" java.lang.NoClassDefFoundError: scala.collection.immutable.Vector
   at java.lang.Class.initializeClass(libgcj.so.10)
   at scala.collection.immutable.Vector$.<init>(Vector.scala:34)
   at scala.collection.immutable.Vector$.<clinit>(Vector.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at scala.package$.<init>(package.scala:78)
   at scala.package$.<clinit>(package.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at scala.Predef$.<init>(Predef.scala:90)
   at scala.Predef$.<clinit>(Predef.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at io.prediction.tools.console.txt.main$.apply(main.template.scala:16)
   at io.prediction.tools.console.Console$.<init>(Console.scala:780)
   at io.prediction.tools.console.Console$.<clinit>(Console.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at io.prediction.tools.console.Console.main(Console.scala)
Caused by: java.lang.ClassFormatError: scala.collection.parallel.immutable.ParVector (erroneous type descriptor)
   at java.lang.VMClassLoader.defineClass(libgcj.so.10)
   at java.lang.ClassLoader.defineClass(libgcj.so.10)
   at java.security.SecureClassLoader.defineClass(libgcj.so.10)
   at java.net.URLClassLoader.findClass(libgcj.so.10)
   at java.lang.ClassLoader.loadClass(libgcj.so.10)
   at java.lang.ClassLoader.loadClass(libgcj.so.10)
   at java.lang.Class.initializeClass(libgcj.so.10)
   ...14 more

**Comment by samirissa00** [comment]
Variables problems !
